[workspace]

members = [


    "client",
    "datastore",
    "ecs",
    "ecs_components",
    "ecs_core",
    "ecs_derive",

    "frontend",
    "logging",


    "physics",
    "protos",
]

[profile.bench]
lto = true
panic = "abort"

[profile.release]
lto = true
panic = "abort"
