[workspace]

members = [
    "cached_hash_map",
    "chunked_grid",
    "datastore",
    "ecs",
    "ecs_derive",
    "nzslab",
    "physics",
    "protos",
    "self_organizing_list",
    "sonifier",
]

[profile.bench]
lto = true
panic = "abort"

[profile.release]
lto = true
panic = "abort"
