[workspace]

members = [
    "cached_hash_map",
    "chunked_grid",
    "ecs",
    "ecs_derive",
    "nzslab",
    "physics",
    "self_organizing_list",
    "sparse_u32_map",
]

[profile.bench]
lto = true
panic = "abort"

[profile.release]
lto = true
panic = "abort"
