# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frontend.proto',
  package='frontend',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x66rontend.proto\x12\x08\x66rontend\"5\n\x08MenuItem\x12\r\n\x05label\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x12\x0b\n\x03key\x18\x03 \x02(\t\"E\n\x04Menu\x12\r\n\x05title\x18\x01 \x02(\t\x12!\n\x05items\x18\x02 \x03(\x0b\x32\x12.frontend.MenuItem\x12\x0b\n\x03key\x18\x64 \x02(\t\"\x1b\n\x0cGameplayArea\x12\x0b\n\x03key\x18\x64 \x02(\t\"e\n\tUiElement\x12\x1c\n\x04menu\x18\x01 \x01(\x0b\x32\x0e.frontend.Menu\x12-\n\rgameplay_area\x18\x02 \x01(\x0b\x32\x16.frontend.GameplayArea\x12\x0b\n\x03key\x18\x64 \x02(\t\"0\n\x07UiStack\x12%\n\x08\x65lements\x18\x01 \x03(\x0b\x32\x13.frontend.UiElement'
)




_MENUITEM = _descriptor.Descriptor(
  name='MenuItem',
  full_name='frontend.MenuItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='frontend.MenuItem.label', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='frontend.MenuItem.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='frontend.MenuItem.key', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=81,
)


_MENU = _descriptor.Descriptor(
  name='Menu',
  full_name='frontend.Menu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='frontend.Menu.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='frontend.Menu.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='frontend.Menu.key', index=2,
      number=100, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=152,
)


_GAMEPLAYAREA = _descriptor.Descriptor(
  name='GameplayArea',
  full_name='frontend.GameplayArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='frontend.GameplayArea.key', index=0,
      number=100, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=181,
)


_UIELEMENT = _descriptor.Descriptor(
  name='UiElement',
  full_name='frontend.UiElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='menu', full_name='frontend.UiElement.menu', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameplay_area', full_name='frontend.UiElement.gameplay_area', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='frontend.UiElement.key', index=2,
      number=100, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=284,
)


_UISTACK = _descriptor.Descriptor(
  name='UiStack',
  full_name='frontend.UiStack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='frontend.UiStack.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=334,
)

_MENU.fields_by_name['items'].message_type = _MENUITEM
_UIELEMENT.fields_by_name['menu'].message_type = _MENU
_UIELEMENT.fields_by_name['gameplay_area'].message_type = _GAMEPLAYAREA
_UISTACK.fields_by_name['elements'].message_type = _UIELEMENT
DESCRIPTOR.message_types_by_name['MenuItem'] = _MENUITEM
DESCRIPTOR.message_types_by_name['Menu'] = _MENU
DESCRIPTOR.message_types_by_name['GameplayArea'] = _GAMEPLAYAREA
DESCRIPTOR.message_types_by_name['UiElement'] = _UIELEMENT
DESCRIPTOR.message_types_by_name['UiStack'] = _UISTACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MenuItem = _reflection.GeneratedProtocolMessageType('MenuItem', (_message.Message,), {
  'DESCRIPTOR' : _MENUITEM,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:frontend.MenuItem)
  })
_sym_db.RegisterMessage(MenuItem)

Menu = _reflection.GeneratedProtocolMessageType('Menu', (_message.Message,), {
  'DESCRIPTOR' : _MENU,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:frontend.Menu)
  })
_sym_db.RegisterMessage(Menu)

GameplayArea = _reflection.GeneratedProtocolMessageType('GameplayArea', (_message.Message,), {
  'DESCRIPTOR' : _GAMEPLAYAREA,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:frontend.GameplayArea)
  })
_sym_db.RegisterMessage(GameplayArea)

UiElement = _reflection.GeneratedProtocolMessageType('UiElement', (_message.Message,), {
  'DESCRIPTOR' : _UIELEMENT,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:frontend.UiElement)
  })
_sym_db.RegisterMessage(UiElement)

UiStack = _reflection.GeneratedProtocolMessageType('UiStack', (_message.Message,), {
  'DESCRIPTOR' : _UISTACK,
  '__module__' : 'frontend_pb2'
  # @@protoc_insertion_point(class_scope:frontend.UiStack)
  })
_sym_db.RegisterMessage(UiStack)


# @@protoc_insertion_point(module_scope)
