[package]
name = "ammo_chunked_array"
version = "0.1.0"
authors = ["Austin Hicks <ahicks@ahicks.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
proptest = "1.0.0"
