[package]
name = "ammo_framer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
derive_more = "0.99.17"
thiserror = "1.0.30"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
